name: Treasure Workflow Deploy

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        # Treasure Workflow API Endpoint
        td_wf_endpoint: api-workflow.treasuredata.com
        # Treasure Data Master API
        td_master_apikey: ${{ secrets.td_master_apikey }}
      run: |
        curl -o ~/bin/digdag --create-dirs -L "https://dl.digdag.io/digdag-latest"
        chmod +x ~/bin/digdag
        digdag push project1 --project project1 $td_wf_endpoint -X client.http.headers.authorization="TD1 $td_master_apikey"
        digdag push project2 --project project2 $td_wf_endpoint -X client.http.headers.authorization="TD1 $td_master_apikey"

