name: Treasure Workflow Deploy

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/
      env:
        # Treasure Workflow API Endpoint
        td_wf_endpoint: api-workflow.treasuredata.com
        # Treasure Data Master API
        td_master_apikey: ${{ secrets.td_master_apikey }}
